# Generated by Django 2.2.10 on 2021-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210605_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(default='uhhh...', max_length=360),
            preserve_default=False,
        ),
    ]
