# Generated by Django 2.2.10 on 2021-06-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210605_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
    ]
