# Generated by Django 3.2.4 on 2021-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210614_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(related_name='answer_choices', to='polls.Choice'),
        ),
    ]
